version: '3.8'

services:
  node1:
    build: .
    container_name: mpi_node1
    hostname: node1
    tty: true
    stdin_open: true
    networks:
      - mpinet
    volumes:
      - ./shared:/app/shared

  node2:
    build: .
    container_name: mpi_node2
    hostname: node2
    tty: true
    stdin_open: true
    networks:
      - mpinet
    volumes:
      - ./shared:/app/shared

  node3:
    build: .
    container_name: mpi_node3
    hostname: node3
    tty: true
    stdin_open: true
    networks:
      - mpinet
    volumes:
      - ./shared:/app/shared

  node4:
    build: .
    container_name: mpi_node4
    hostname: node4
    tty: true
    stdin_open: true
    networks:
      - mpinet
    volumes:
      - ./shared:/app/shared

networks:
  mpinet:
    driver: bridge